### ISSUE TITLE
modules/services/holochain-conductor: make sure nothing mutates config

### ISSUE THREAD

**Issue by yegortimoshenko** [Holo-Host/holo-nixpkgs#113]
Configuration files traditionally are not supposed to be mutated at runtime. The problem lies with Holo Envoy doing what Nix is supposed to do with regards to managing hApp packages directly and mutating the conductor config.

What it should do instead is it should generate a JSON config declaring hApps that need to be installed, that Nix can then use to rebuild conductor config and atomically update the set of packages.

**Comment by alastairong** [comment]
@peeech Is this still relevant given the work we've done on conductor-config rebuild?

**Comment by alastairong** [comment]
Closed in a different way via #470
