### ISSUE TITLE
Set up Hydra instances to use master Nix channel

### ISSUE THREAD

**Issue by sowelisuwi** [Holo-Host/holo-nixpkgs#124]
Currently, Hydra master instance follows `develop` [which has a relatively lax commit policy](https://github.com/Holo-Host/holo-nixpkgs/blob/df2be38da712bcfa9254c58c3611bfb8e65603e0/CONTRIBUTING.md#branch-protection-rules).

Use `master` instead. Additionally, evaluate #120 security/convenience tradeoffs.

**Comment by alastairong** [comment]
@peeech Closing as I'm pretty sure we don't  want this.
