### ISSUE TITLE
modules/system/holoportos: autoUpgrade is not specific to HPOS

### ISSUE THREAD

**Issue by yegortimoshenko** [Holo-Host/holo-nixpkgs#177]
Auto-upgrade can be used on our production systems (like `profiles/hydra` and `profiles/gateway`). Thus, it is not HPOS-specific and needs to be renamed.

**Comment by samrose** [comment]
Does this just need to move up in the source tree so that it is available to all relevant profiles, in addition to being renamed?

**Comment by yegortimoshenko** [comment]
It is already available to all profiles. I would just like to see it renamed to `system.holo-nixpkgs.autoUpgrade`. Probably, whole `system.holoportos` will be better off renamed to `system.holo-nixpkgs`.
