### ISSUE TITLE
Add git revision to Nixos version file

### ISSUE THREAD

**Issue by samrose** [Holo-Host/holo-nixpkgs#183]

**Comment by yegortimoshenko** [comment]
This needs clarification from @samrose.

**Comment by samrose** [comment]
Clarification: somewhere appropriate, we should write out the specific git revision that the currently built and running nixos version of holo-nixpkgs is based from. Unless this is already somehow visible in the running OS somewhere?

**Comment by samrose** [comment]
@yegortimoshenko ...or if you have some reason we *shouldn't* do this?

**Comment by yegortimoshenko** [comment]
There is a requirement to implement this in a way that doesn't cause unnecessary rebuilds. To do that, one will need to add attrs to `release.nix` arg attrset.

**Comment by alastairong** [comment]
Done but the file is `/root/.nix-revision` #512
