### ISSUE TITLE
profiles/hardware/qemu: fix nix-shell inside holoportos-shell

### ISSUE THREAD

**Issue by yegortimoshenko** [Holo-Host/holo-nixpkgs#184]
Currently, Nix channel is not being correctly set inside `holoportos-shell`, which results in broken `nix-shell`. Until this is fixed, workaround is to add entries to `environment.systemPackages` in `profiles/holoportos/default.nix`.

cc @mjbrisebois

**Comment by alastairong** [comment]
we don't even have a holoportos-shell anymore.
