### ISSUE TITLE
hpos-reset: add a script that resets system state

### ISSUE THREAD

**Issue by yegortimoshenko** [Holo-Host/holo-nixpkgs#188]
Original implementation could be as simple as:

```
tmp=$(mktemp -d)
cp -r /etc/nixos "$tmp"
rm -r /etc /home /root /var
mv "$tmp" /etc/nixos
```

In addition to that, early systemd module should check for a flag in `hpos-config.json` or a special file on USB drive.

**Comment by samrose** [comment]
@alastairong expanded on this, that the requirement is that it needs to be a script that can be downloaded, copied to USB, inserted and automatically run

**Comment by yegortimoshenko** [comment]
Resolved in https://github.com/Holo-Host/holo-nixpkgs/commit/73f117a54abcd5a6248be1ef411643c33ef8a59e.

**Comment by alastairong** [comment]
Reopening until this script can be initiated via USB drive
