### ISSUE TITLE
tests: restore envoy test

### ISSUE THREAD

**Issue by samrose** [Holo-Host/holo-nixpkgs#193]
Envoy test was removed per https://github.com/notifications/beta/MDE4Ok5vdGlmaWNhdGlvblRocmVhZDY0NDAwMTk4ODoxMTU4MjE=?custom_inbox=true&query=reason%3Areview-requested#pullrequestreview-327044898

Due to forward incompatibility.

This is an issue to recreate this test under new envoy funcitonality

**Comment by yegortimoshenko** [comment]
We're going to replace Envoy, and functionality set it is going to offer will be quite different. With that in mind, old test is unlikely to apply.
