### ISSUE TITLE
Integrate centralized logging into HoloPortOS

### ISSUE THREAD

**Issue by sowelisuwi** [Holo-Host/holo-nixpkgs#247]
https://help.papertrailapp.com/kb/configuration/configuring-centralized-logging-from-systemd/#using-socat

**Comment by yegortimoshenko** [comment]
This has been requested by @peeech. I think we can actually reasonably issue a separate token for each HoloPort, maybe as part of auth flow.

**Comment by peeech** [comment]
That looks great. We can call it a log token and in the future have a user initiated action of deleting the token from system whenever someone would request anonymization.

**Comment by yegortimoshenko** [comment]
FTR, I mean we auth HoloPort, and ask Papertrail to issue a token for them. Then communicate said token back to HoloPort.

**Comment by alastairong** [comment]
@peeech Closing as we're doing other monitoring work. Future error logging may be handled via servicelogger. Regardless, we will track logging via feature tickets.
