### ISSUE TITLE
Move static assets over to Cloudflare Workers Sites

### ISSUE THREAD

**Issue by yegortimoshenko** [Holo-Host/holo-nixpkgs#269]
See: https://blog.cloudflare.com/workers-sites/

Since now we have Cloudflare CI/CD (see https://github.com/Holo-Host/holo-cache repo for example), we can leverage better cache invalidation by moving this stuff over to Cloudflare.

- [x] `hpstatus.holo.host`
- [x] `quickstart.holo.host`

**Comment by alastairong** [comment]
This has been done for Quickstart.holo.host right? 
Has it been done for hpstatus.holo.host too?

**Comment by yegortimoshenko** [comment]
This has been addressed for both.
