### ISSUE TITLE
Harden all custom systemd units

### ISSUE THREAD

**Issue by abelianring** [Holo-Host/holo-nixpkgs#273]
Currently, most of our systemd units run as root, which is completely unacceptable. We should go the opposite direction and make sure that all units more or less only have access to resources that are actually required. That would mean not just hardening offered by `DynamicUser`, but full-on network sandboxing, hiding `/dev`, W^X restriction where possible, and so on.

For some relevant systemd options, see: https://gist.github.com/ageis/f5595e59b1cddb1513d1b425a323db04

- [ ] `services/aorura-emu.nix`
- [ ] `services/dnscrypt-proxy2.nix`
- [ ] `services/holo-auth-client.nix`
- [ ] `services/holo-router-agent.nix`
- [ ] `services/holo-router-gateway.nix`
- [ ] `services/holochain-conductor.nix`
- [ ] `services/hp-admin-crypto-server.nix`
- [ ] `services/hpos-admin.nix`
- [ ] `services/hpos-led-manager.nix`
- [ ] `services/magic-wormhole-mailbox-server.nix`
- [ ] `services/sim2h-server.nix`

**Comment by alastairong** [comment]
@peeech Is this still necessary now that you've created profiles for the various services?

**Comment by alastairong** [comment]
Closed as completed.
