### ISSUE TITLE
Instruction on how to set up a production grade holoport

### ISSUE THREAD

**Issue by jacob3141** [Holo-Host/holo-nixpkgs#287]
I have my own hardware left over, that's why I did not order a holoport but other perks. Back then it was advertised that the holport OS could be run on your hardware, which is kind of true, but I cannot find instructions that clearly state which steps to perform to end up with an equivalent of a HoloPort.

I already tried to install NixOS in a Hyper-V test environment (VirtualBox is not an option, since it is not able to coexist with Hyper-V), generated some config files and added the lines mentioned in the README, hoping that it would magically work (of course it doesn't). After installing git and cloning the development environment, when running hpos-shell I get some weird error pc.ram could not be allocated (the VM was assigned 32GBs..).

Can you shed a light on this? Thank you very much!

**Comment by jacob3141** [comment]
Nevermind the ram allocation memory issue, I figured this is an issue with Hyper-V and dynamically allocated memory. As soon as I assign the machine a fixed 32GBs it works with qemu inside Hyper-V. So how would I permanently turn the NixOS host operating system into a HoloportOS system?

**Comment by jacob3141** [comment]
So I finally gave up and tried the virtual box image. The machine boots up and I managed to get through the registration process ending up with a hpos-config.json. I have that file over to USB and propagated it to the VBox guest.

Nothing happens. So I went and saw that presumably the device is not being automounted and mounted it manually in /media/usb. Still nothing happened, so I decided to check the systemd services and found that the holoportos-upgrade.service exited with error code 1. 

Is this expected?

**Comment by yegortimoshenko** [comment]
For general support, I'd recommend you visit <https://forum.holo.host>. WRT Hyper-V, we don't support generic targets just yet, only HoloPort/HoloPort+ and VirtualBox. We'll add a generic x86 target soon-ish, which will be good enough for a Hyper-V, QEMU, and most IBM compatible hardware.

If you don't mind, I'll rephrase title of this issue to reflect this solution.

**Comment by jacob3141** [comment]
Ok, I will wait for the generic solution then (I thought the HoloPort-Version will do just fine with some exceptions, such as as the LED indicator, which is not present of course on generic hardware).

So considering the VirtualBox image does not work ootb (but should), all that remains would then be a bug report that it does not work from my side (see details above) :) As I said, I am not sure if the current version is just broken? I am happy to provide you with details thought if need be.

**Comment by samrose** [comment]
@jacob3141 if you are still trying to use the VirtualBox image, Holo requests that you visit https://forum.holo.host/ and post an issue there. Thank you!

**Comment by jacob3141** [comment]
@samrose Done. Not sure if this is the right spot to post issues there though. https://forum.holo.host/t/https-github-com-holo-host-holo-nixpkgs-issues-287/1025?u=jada

**Comment by yegortimoshenko** [comment]
I filed #290 as generic installer issue. Thank you! For general support (things not working, etc.) it's best to go through forum support.
