### ISSUE TITLE
Implement rescue image

### ISSUE THREAD

**Issue by samrose** [Holo-Host/holo-nixpkgs#296]
For some customer support cases, we will need a rescue image that will allow a customer with functional hardware to attempt to re-install or rescue their holoport 

The scope of this *should be limited* to problems with booting the OS, and where there is not an existing way to solve it without rescue.

**Comment by alastairong** [comment]
@samrose What's the status of this? I'm thinking it might be good to pick up for our next sprint

**Comment by samrose** [comment]
@alastairong I don't think any progress has been made on it. I don't mind taking it on. Probably would need some collaboration with @yegortimoshenko  as they had some specific ideas on this

**Comment by alastairong** [comment]
@samrose I think this is quite important, but https://github.com/Holo-Host/holo-nixpkgs/issues/188 is higher priority and I've added that story to the backlog. Is that something you can work on?

**Comment by alastairong** [comment]
Done
