### ISSUE TITLE
Implement hpos-config.json schema validation

### ISSUE THREAD

**Issue by peeech** [Holo-Host/holo-nixpkgs#298]
Currently HPOS admin API will accept any config and write it to the hpos-config.json file as long as it's properly formatted json string. This can result in erasing field `v1.settings.admin` which results in bricking HPOS. 

We currently do not have the way to recover hpos-config.json from seed. I think that writing over `v1.settings.admin` should be disabled.

**Comment by yegortimoshenko** [comment]
I updated the issue title to signify that actually more than one component is affected (not only HPOS Admin, but HPOS Init as well).

**Comment by peeech** [comment]
Resolved in #410
