### ISSUE TITLE
Make the holofuel UI functional in hp admin

### ISSUE THREAD

**Issue by samrose** [Holo-Host/holo-nixpkgs#312]
Logged in users can successfully navigate to <pubkey>.holohost.net/holofuel

Depends on #300

**Comment by peeech** [comment]
resolved in #325

**Comment by yegortimoshenko** [comment]
See: https://github.com/Holo-Host/holo-nixpkgs/issues/319#issuecomment-578501456

**Comment by peeech** [comment]
Resolved in #365
