### ISSUE TITLE
Develop components that will allow hp admin users to see their holofuel address

### ISSUE THREAD

**Issue by samrose** [Holo-Host/holo-nixpkgs#313]
Logged in users can see their HoloFuel address

**Comment by samrose** [comment]
depends on #312

**Comment by peeech** [comment]
This is more of the UI issue. `holofuel/transactions/whoami` zome call returns `agent_address: "HcSCjBHI9StQ3arsa93HnGdbE37Dg8gxyfEV6OXDTYk8dcj8K8VajhAbNigskra"` but it seems to be never displayed explicitly to the user.
