### ISSUE TITLE
Deploy changes to release candidate branch for holofuel ui in hp admin

### ISSUE THREAD

**Issue by samrose** [Holo-Host/holo-nixpkgs#315]
Changes are deployed to release candidate branch for internal testing

Depends on #312 #313 #314 #310

**Comment by peeech** [comment]
resolved in #325

**Comment by yegortimoshenko** [comment]
See: https://github.com/Holo-Host/holo-nixpkgs/issues/319#issuecomment-578501456

**Comment by peeech** [comment]
Resolved in #365
