### ISSUE TITLE
Deploy changes to release candidate branch that allows users to send test fuel

### ISSUE THREAD

**Issue by samrose** [Holo-Host/holo-nixpkgs#319]
Depends on #310 #318 #316

**Comment by peeech** [comment]
rsolved in #325

**Comment by yegortimoshenko** [comment]
@peeech: Please only close issues once they have been merged in.

**Comment by yegortimoshenko** [comment]
You can use Zenhub "In review" state to reflect that this is ready to review. Do you have access? If you don't like Zenhub, we can try GitHub Projects instead.

**Comment by peeech** [comment]
Resolved in #365
