### ISSUE TITLE
Use specific sim2h servers for different dnas

### ISSUE THREAD

**Issue by peeech** [Holo-Host/holo-nixpkgs#351]
Each self hosted DNA has to operate on it's own sim2h server provided by HoloCentral. This can be achieved by adding a `sim2h_url` prop to root manifest json of a DNA (see [this blog post](https://blog.holochain.org/sim2h-holochains-simple-switch-board-networking/#running-your-own-switch-board-server).

List of servers:
- hosting.sim2h.net
- happstore.sim2h.net
- servicelogger.sim2h.net
- communities.sim2h.net
- holofuel.sim2h.net
- public.sim2h.net
- test.sim2n.net

DNA specific sim2h_urls override global network.sim2h_url setting, which should be ws://public.sim2h.net.

**Comment by alastairong** [comment]
Should this issue be closed? And a new one opened about them not working?

**Comment by peeech** [comment]
Actually we are moving back to one sim2h_url

**Comment by alastairong** [comment]
XD
