### ISSUE TITLE
Implement new LED states in hpos-led-manager

### ISSUE THREAD

**Issue by yegortimoshenko** [Holo-Host/holo-nixpkgs#353]
@zo-el Which issues did you run into?

**Comment by zo-el** [comment]
@yegortimoshenko, Can we document how to locally run and test the [hpos-led-manager](https://github.com/Holo-Host/holo-nixpkgs/tree/develop/overlays/holo-nixpkgs/hpos-led-manager) project?

**Comment by alastairong** [comment]
No longer needed from product / UX perspective
