### ISSUE TITLE
Deploy holo-nixpkgs hpos profile to an instance of packet.net (hpos-3)

### ISSUE THREAD

**Issue by samrose** [Holo-Host/holo-nixpkgs#355]
@robbiecarlton my request was left for tech services at https://chat.holochain.org/holo/pl/kzzz1m8fzpdsud6crsbyr5i7fw

@robbiecarlton @zo-el can you confirm whether you need just a running instance of holoportos that you can control and reconfigure? If so, this is probably the best bet for using an external server, and I can help you work through here how you would go about using it. Let me know if you think just using an instance of hpos can work for you

**Comment by robbiecarlton** [comment]
Thanks @samrose!

I *think* it's going to be better if I am running hpos-shell inside of a server, so that I can make and test changes faster. But @zo-el has done the research on this so I'll defer to him.

**Comment by samrose** [comment]
@robbiecarlton @zo-el we can try running hpos-shell this way. If it doesn't work we can create plan b to deploy hpos itself.

**Comment by samrose** [comment]
This is completed. Instructions delivered to @robbiecarlton

**Comment by samrose** [comment]
(I confirmed that hpos-shell will work via terminal from an ubuntu desktop on this remote server)

**Comment by yegortimoshenko** [comment]
@samrose Please label issues.

**Comment by yegortimoshenko** [comment]
How did you set it up so that I don't have access?

```
$ ssh root@robbie.holotest.dev
root@robbie.holotest.dev: Permission denied (publickey).
```

**Comment by yegortimoshenko** [comment]
In particular, I'm wondering how `/etc/nixos/configuration.nix` looks like.

**Comment by samrose** [comment]
Sigh. Someone must have changed the configuration.nix

the way I left it, it had public keys for @robbiecarlton @yegortimoshenko @samrose

**Comment by samrose** [comment]
> @samrose Please label issues.

What are you labeling conventions?

**Comment by samrose** [comment]
@robbiecarlton did you or @zo-el happen to change the /etc/nixos/configuration.nix on this machine?

If so, and if you cannot login @robbiecarlton we will likely need to redeploy it.

**Comment by samrose** [comment]
I have followed up

**Comment by samrose** [comment]
Errors logged

https://gist.githubusercontent.com/samrose/39adfe06d69b6aa3ca10368b12e96aed/raw/870914dd10ad7302f645fa2e784b25ad9baefccd/hpos-3

**Comment by samrose** [comment]
I found reference to https://github.com/NixOS/nixpkgs/issues/31540 

supposedly `systemd-timesyncd.service` is supposed to `rm -rf {/var/lib/systemd/timesync,/var/lib/private/systemd/timesync}`

Problem not yet resolved upstream

**Comment by samrose** [comment]
Performing that action manually does turn on `systemd-timesyncd.service`

```
systemctl status systemd-timesyncd.service
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/nix/store/x58q7zabmnkq0qall5d72d396fxmz8cd-systemd-243.3/example/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enabl>
  Drop-In: /nix/store/l4crgkvnhx9nlminbjz7h8dzlhm2rl3n-system-units/systemd-timesyncd.service.d
           └─overrides.conf
   Active: active (running) since Thu 2020-02-06 22:18:43 UTC; 48s ago
     Docs: man:systemd-timesyncd.service(8)
 Main PID: 17417 (systemd-timesyn)
   Status: "Initial synchronization to time server 69.10.161.7:123 (0.nixos.pool.ntp.org)."
       IP: 76B in, 76B out
    Tasks: 2 (limit: 4915)
   Memory: 1.1M
      CPU: 539ms
   CGroup: /system.slice/systemd-timesyncd.service
           └─17417 /nix/store/x58q7zabmnkq0qall5d72d396fxmz8cd-systemd-243.3/lib/systemd/systemd-timesyncd

Feb 06 22:18:42 hpos-3.holo.host systemd[1]: Starting Network Time Synchronization...
Feb 06 22:18:43 hpos-3.holo.host systemd[1]: Started Network Time Synchronization.
Feb 06 22:18:43 hpos-3.holo.host systemd-timesyncd[17417]: Initial synchronization to time server 69.10.161.7:123 (0.nixos.pool.ntp.org).
```

However, the following step still hangs

```
nix-channel --add https://github.com/Holo-Host/holo-nixpkgs/archive/develop.tar.gz holo-nixpkgs
nix-channel --update
nix-channel --remove nixos
nixos-rebuild switch \
  -I holo-nixpkgs=/nix/var/nix/profiles/per-user/root/channels/holo-nixpkgs \
  -I nixpkgs=/nix/var/nix/profiles/per-user/root/channels/holo-nixpkgs/nixpkgs \
  -I nixpkgs-overlays=/nix/var/nix/profiles/per-user/root/channels/holo-nixpkgs/overlays
```

**Comment by samrose** [comment]
rebooted machine

now this succeeds:

```
nixos-rebuild switch --upgrade 
unpacking channels...
unpacking channels...
building Nix...
building the system configuration...
updating GRUB 2 menu...
activating the configuration...
setting up /etc...
reloading user units for root...
setting up tmpfiles

```

The profile is now successfully configured
