### ISSUE TITLE
Intermittent 500 errors in Wasabi US-East-1 zone break cache.holo.host

### ISSUE THREAD

**Issue by peeech** [Holo-Host/holo-nixpkgs#364]
I am getting multiple `500` errors while trying to build derivations in nix-shell. When trying to build derivation or enter nix-shell (that builds dependencies) I am getting cache.holo.host errors:

```
copying path '/nix/store/277k7n916ds50w9ddr1ig03nmqb9ihqm-holochain-rust' from 'https://cache.holo.host'...
unable to download 'https://cache.holo.host/nar/1zszpflig5rwgywypd13xj2c2gn1xmwp948af1irvkqvhay33igm.nar.xz': HTTP error 500
cannot build derivation '/nix/store/qfnvnknrz8g6mmihr7d2ibjpj9bhpnx0-happ-store-hash.drv': 1 dependencies couldn't be built
```
and
```
copying path '/nix/store/gm9ydsq3pag3jpzfy5ib3gxpgn7v20jk-cargo-1.37.0' from 'https://cache.holo.host'...
unable to download 'https://cache.holo.host/nar/0501fkp35jkb4cgd435pkclq95s0jmvzrkzxdba7vkgv2x6bwvw0.nar.xz': HTTP error 500
cannot build derivation '/nix/store/w9li25n786p9yvn29r0zkk5pkqgs2pm3-nixpkgs-fmt-0.5.0.drv': 1 dependencies couldn't be built
```
and
```
copying path '/nix/store/b94k2szmdqvxzk5ak5f5nvk6fv32dl4g-source' from 'https://cache.holo.host'...
unable to download 'https://cache.holo.host/nar/0pzpzy48d57n38669kg9qjyxnklm4wy1fnlmg5gd093vdfsxj1ir.nar.xz': HTTP error 500
```

**To reproduce**
Check out holo-nixpkgs `develop` branch and enter nix-shell.

**Comment by yegortimoshenko** [comment]
This is now resolved. [Wasabi](https://wasabi.com) runs into `500` s sometimes, not much we can do with that. Their newer availability zones are supposed to be more reliable.

**Comment by peeech** [comment]
This seems to be not a random issue, but very specific (and repeatedly happening) to the assets listed above. Obviously this list is not complete, but on my machine it's 100% reproducible.

**Comment by yegortimoshenko** [comment]
Hydra is currently running into the same issue:

> Feb 03 11:34:06 hydra.holo.host hydra-queue-runner[114643]: AWS error 'InternalError' (We encountered an internal error.  Please retry the operation again later.), will retry in 0 ms

**Comment by yegortimoshenko** [comment]
> This seems to be not a random issue, but very specific (and repeatedly happening) to the assets listed above. Obviously this list is not complete, but on my machine it's 100% reproducible.

It is definitely random, given both my past experience (this is a recurring issue) and given that I tried fetching URLs before replying in https://github.com/Holo-Host/holo-nixpkgs/issues/364#issuecomment-581361900 and they all worked. They stopped working and result in 500 again.

**Comment by peeech** [comment]
ok, so it seems that it comes in waves 😸 . How can I temporarily disable using cache?

**Comment by yegortimoshenko** [comment]
Add `--option substituters ''` to `nix-build` or `nix-shell` command.

**Comment by peeech** [comment]
Perf, thanks!

**Comment by yegortimoshenko** [comment]
```xml
$ curl -v 'https://cache.holo.host/nar/03hnkhvczpd58ky21jfdahfgw6bmmnd147ghgwfyzmzmlahn9rwk.nar.xz'
<Error><Code>InternalError</Code><Message>We encountered an internal error.  Please retry the operation again later.</Message><Detail>Storage:StorSysCantCreateStorRead at=storsys.(*StorSys).Open( storsys/storsys.go:1887 )</Detail><RequestId>1A8E4483A512568E</RequestId><HostId>t50vXehBpSegJKpzpT+5nmN6xLstW2X/N0HcU+lNXpkXQkoo+zpMKCUFqVbcaDf61IBjv5EsVSUi</HostId></Error>
```

**Comment by yegortimoshenko** [comment]
https://status.wasabi.com reports an issue, again specifically with our data center. Maybe we should migrate after all...

**Comment by peeech** [comment]
+1 from me because it takes eternity to build without cache.

**Comment by alastairong** [comment]
I'm getting a 503 error when trying to download the VM from https://hydra.holo.host/build/14803. Assuming this is related?

**Comment by yegortimoshenko** [comment]
@alastairong It is related. Although, it seemed to work for me just now. Could you retry?

**Comment by alastairong** [comment]
Yea it works for me now.

**Comment by alastairong** [comment]
This 500 issue is blocking QA from testing so unfortunately now becoming urgent. :/

Is there a short term workaround?

Error log from Mary's HoloPort below:
[staging-upgrade-service.log](https://github.com/Holo-Host/holo-nixpkgs/files/4153328/staging-upgrade-service.log)

**Comment by alastairong** [comment]
Does wasabi impact master too or just staging? I.e. should we expect auto-update errors for our customers too?

**Comment by peeech** [comment]
I think so. Some of assets on Wasabi are returning 500 and per their [support page](https://status.wasabi.com/) this has been happening for a while.

**Comment by yegortimoshenko** [comment]
Resolved: https://status.wasabi.com/pages/history/5abbc12aeb57a904e44a58d3#5e3825953f4deb04c0d7f77b
