### ISSUE TITLE
Nginx and hpos-admin cannot communicate over hpos-admin.sock

### ISSUE THREAD

**Issue by peeech** [Holo-Host/holo-nixpkgs#366]
hpos-admin service is not accessible from nginx, because of wrong hpos-admin.sock permissions.

**to reproduce**
Checkout #365 and build HPOS, run it and observe the log. Client side error:
```
https://46uuouiqk0k2jmkh310fvg9c87gns29fqdrc8pej0ynmuhh3f8.holohost.net/api/v1/config
Status Code: 502 Bad Gateway
```
Server side error:
```
Feb 04 16:02:05 hpos nginx[639]: 2020/02/04 16:02:05 [crit] 842#842: *7 connect() to unix:/run/hpos-admin.sock failed (13: Permission denied) while connecting to upstream, client: 172.26.50.86, server: default, request: "GET /api/v1/config HTTP/2.0", upstream: "http://unix:/run/hpos-admin.sock:/api/v1/config", host: "46uuouiqk0k2jmkh310fvg9c87gns29fqdrc8pej0ynmuhh3f8.holohost.net", referrer: "https://46uuouiqk0k2jmkh310fvg9c87gns29fqdrc8pej0ynmuhh3f8.holohost.net/"
```

**Comment by peeech** [comment]
cc @yegortimoshenko

**Comment by yegortimoshenko** [comment]
Best way to resolve this would be to add a group that both `nginx` user and dynamic user that runs `hpos-admin` would be inside of, and then `chown` the Unix socket. Will do.

**Comment by peeech** [comment]
Great, that's what I was hoping for. But have no idea how to do it...
