### ISSUE TITLE
Switching a holoport to a pr channel results in path not found error 

### ISSUE THREAD

**Issue by samrose** [Holo-Host/holo-nixpkgs#375]
Steps to recreate:

```
nix-channel --add https://hydra.holo.host/channel/custom/holo-nixpkgs/365/holo-nixpkgs
nix-channel --update
systemctl start holo-nixpkgs-auto-upgrade.service
```
(system successfully updates to this channel)

run

`nix-env -qa '*'`

result

![IMG_0438](https://user-images.githubusercontent.com/115821/74204916-24ac1a80-4c43-11ea-8321-1ebb5ce6628f.jpg)

**Comment by samrose** [comment]
@alastairong @yegortimoshenko this is in reference to my attempt to support Alastair switching a holoport to the 365 PR channel

**Comment by samrose** [comment]
(issue here seems to be that the machine doesn't appear to fully switch to the version being served on the channel as expected)

**Comment by samrose** [comment]
I will guess this is  a white elephant issue until more evidence comes to light

**Comment by alastairong** [comment]
Yup. Seems to work fine now
