### ISSUE TITLE
Upstream magic-wormhole-mailbox-server to Nixpkgs

### ISSUE THREAD

**Issue by yegortimoshenko** [Holo-Host/holo-nixpkgs#383]
https://github.com/Holo-Host/holo-nixpkgs/blob/develop/modules/services/magic-wormhole-mailbox-server.nix
https://github.com/Holo-Host/holo-nixpkgs/blob/develop/overlays/holo-nixpkgs/magic-wormhole-mailbox-server/default.nix

Derivation [is missing `meta` block](https://nixos.org/nixpkgs/manual/#chap-meta) and NixOS module would benefit from [leveraging dynamic users](http://0pointer.net/blog/dynamic-users-with-systemd.html).

cc @samrose

**Comment by samrose** [comment]
First I am doing https://github.com/Holo-Host/holo-nixpkgs/pull/393  for our own short term internal use (plus to just test that it will work). Once that is working well, I will then upstream this as the next step.

**Comment by mmahut** [comment]
Upstreamed in https://github.com/NixOS/nixpkgs/pull/83768.

**Comment by yegortimoshenko** [comment]
Thank you a lot!
