### ISSUE TITLE
virtualbox-image.nix isn't configurable

### ISSUE THREAD

**Issue by yegortimoshenko** [Holo-Host/holo-nixpkgs#384]
For HoloPortOS VM images, we want to disable audio and USB emulation because we don't use USB or audio in HoloPortOS VMs and not all VirtualBox installs support these devices.

Currently we have to patch `virtualbox-image.nix` to achieve that:

https://github.com/Holo-Host/holo-nixpkgs/blob/develop/nixpkgs/src/virtualbox-image-no-audio-mouse-usb.diff

```diff
diff --git a/nixos/modules/virtualisation/virtualbox-image.nix b/nixos/modules/virtualisation/virtualbox-image.nix
index ab65523592d..b0613adcc92 100644
--- a/nixos/modules/virtualisation/virtualbox-image.nix
+++ b/nixos/modules/virtualisation/virtualbox-image.nix
@@ -72,9 +72,7 @@ in {
             --memory ${toString cfg.memorySize} --acpi on --vram 32 \
             ${optionalString (pkgs.stdenv.hostPlatform.system == "i686-linux") "--pae on"} \
             --nictype1 virtio --nic1 nat \
-            --audiocontroller ac97 --audio alsa --audioout on \
-            --rtcuseutc on \
-            --usb on --usbehci on --mouse usbtablet
+            --rtcuseutc on
           VBoxManage storagectl "$vmName" --name SATA --add sata --portcount 4 --bootable on --hostiocache on
           VBoxManage storageattach "$vmName" --storagectl SATA --port 0 --device 0 --type hdd \
             --medium disk.vmdk
```

I'd recommend to send a PR to Nixpkgs that adds `config.virtualbox.params` in `virtualbox-image.nix`, with interface like this:

```nix
{
  virtualbox.params = {
    audiocontroller = "ac97";
    audio = "alsa";
    audioout = true;
    nic1 = "nat";
    nictype1 = "virtio";
    # etc.
  };
}
```

That would require writing a function that converts attrset like `{ foo = "hello"; bar = true; baz = 32;  }` into `[ "--foo hello" "--bar on" "--baz 32" ]`. [See `<nixpkgs/lib>` docs](https://nixos.org/nixpkgs/manual/#sec-functions-library).

cc @samrose

**Comment by mmahut** [comment]
Change proposed upstream at https://github.com/NixOS/nixpkgs/pull/80736.

**Comment by yegortimoshenko** [comment]
Again, thank you :3
