### ISSUE TITLE
HoloPort following a typo'd channel and can't switch back

### ISSUE THREAD

**Issue by alastairong** [Holo-Host/holo-nixpkgs#386]
@marycamacho Accidentally made the following typo:

`nix-channel --add https://hydra.holo.host/channel/custom/holo-nixpkgs/develop/holo-nixpkgs/q`

When she tries to fix it the `/q` remains in the path. So example if she types:

`nix-channel --add https://hydra.holo.host/channel/custom/holo-nixpkgs/master/holo-nixpkgs`
`nix-channel --update`
`nix-channel --list`

It results in: `https://hydra.holo.host/channel/custom/holo-nixpkgs/master/holo-nixpkgs/q`

Any idea what's going on?

CC: @yegortimoshenko @samrose

**Comment by peeech** [comment]
First of all it is always a good idea to use `--help`:
```
nix-channel --help
...
       --remove name
           Removes the channel named name from the list of subscribed channels.
...
```
So:
`nix-channel --remove q`
will do the job

**Comment by alastairong** [comment]
CC: @SirRobLyon

**Comment by alastairong** [comment]
Fix confirmed with Mary.
