### ISSUE TITLE
`hpos-switch` fails to compile in develop and staging branches

### ISSUE THREAD

**Issue by zo-el** [Holo-Host/holo-nixpkgs#387]
Hi @Holo-Host/central,
I have been trying to set up `root@hpos-2.holo.host` for testing. 
And when I run `hpos-switch` it fails to compile and this is the error I get:
![Screenshot from 2020-02-20 16-07-06](https://user-images.githubusercontent.com/29548571/74987606-2b841b80-5401-11ea-9b0e-8e28ae6dee47.png)

**Comment by alastairong** [comment]
CC: @yegortimoshenko @samrose I'll add this to Pivotal too. Please prioritise helping hAppy team as their work on HP Admin UI is currently the blocker to QA and release.

**Comment by yegortimoshenko** [comment]
Even though Avahi failed, system switched to the new configuration. You can ignore this error for now.

**Comment by alastairong** [comment]
CC: @zo-el
