### ISSUE TITLE
Add schema validation to hpos-admin

### ISSUE THREAD

**Issue by yegortimoshenko** [Holo-Host/holo-nixpkgs#389]
Now that `hpos-admin-is-valid` is avaliable (https://github.com/Holo-Host/hpos-config/pull/50), we can just call that with `hpos-config.json` in stdin on every `PUT /v1/config`.

**Comment by peeech** [comment]
or you can pass `json.dumps(state, indent=2)` to the stdin of `hpos-admin-is-valid` right before you save it to disc?

**Comment by yegortimoshenko** [comment]
Sure, that's the intended implementation :)

**Comment by peeech** [comment]
ah, ok. cool!

**Comment by peeech** [comment]
Resolved in #410
