### ISSUE TITLE
root@hpos-2.holo.host -  connection is not private error 

### ISSUE THREAD

**Issue by zo-el** [Holo-Host/holo-nixpkgs#390]
After setting everything up in `hpos-2.holo.host` I receive `SEC_ERROR_UNKNOWN_ISSUER`
when I try to reach it by the `agent_hash.holohost.dev` url

![Screenshot from 2020-02-21 11-00-42](https://user-images.githubusercontent.com/29548571/75055056-eeb83300-5499-11ea-87e5-000f22a3111f.png)

**Comment by yegortimoshenko** [comment]
Your screenshot says `holohost.dev`, while you're supposed to connect to `holohost.net`. Visit the link in the email address. If it still doesn't work, please paste the link here.

**Comment by yegortimoshenko** [comment]
(Please CC, rather than assign people.)

**Comment by zo-el** [comment]
@yegortimoshenko, For the links of the hosted `hpos` we have to visit `holohost.dev` not `holohost.net`, that was the information shared with me.
@peeech can confirm this.

@yegortimoshenko, The link should be private because we don't want other users accessing it.
I'll ping the link in the HoloCentral channel for all of @Holo-Host/central to try it out.

**Comment by yegortimoshenko** [comment]
> @yegortimoshenko, For the links of the hosted hpos we have to visit holohost.dev not holohost.net, that was the information shared with me.

This is no longer the case if you go through `hpos-init` on the box.

> @yegortimoshenko, The link should be private because we don't want other users accessing it.
I'll ping the link in the HoloCentral channel for all of @Holo-Host/central to try it out.

Why not let other users access it? It's password-protected.

**Comment by alastairong** [comment]
Seems like this is resolved. Will close
