### ISSUE TITLE
Aligning Nix use approaches between holonix & holo-nixpkgs

### ISSUE THREAD

**Issue by jmday** [Holo-Host/holo-nixpkgs#396]
# Alignment of Holo and Holochain Nix Approaches
Meeting Recording: [DavidM & Yegor explore current uses, differences, and possibilities for nix use](https://drive.google.com/open?id=1vzKz1lJkF1HYYbDlI9aeXCrfxC_NBW1l) - accessible by holo.host emails only.

### Holochain
- Provides a shell with dependencies that ensure a consistent hApp dev environment (e.g. hc version, proper rust nightlies).
- Allows for easier support across Mac/linux/win platforms.

### Holo
Two major uses of Nix by Holo:
1. Manage dev environments for centralized infrastructure components (e.g. Holo Router/Gateway)
2. Create HPOS (extends NixOS) for Holo Hosting Devices.

### Holochain use
- focuses on providing high ease-of-use for hApp devs
- does not build artifacts using nix
- adds extra tools/scripts that make use as easy as possible.

### Holo’s use
- is more conventional & consistent with the nixos/nixpkgs approach
- builds all artifacts using nix
- integrates binary cache so users don’t have to build everything
- allows for specification of individual / multiple build targets
- integrates CI configuration with build process definition

## Nix Use Challenges
- Writing nix derivations requires a sufficient level of knowledge (many hApp devs may not be interested until they see value/drift issues)
- Many devs want to use `npm run` or use docker containers with preferred tools (chef/puppet/ansible/circleci/travis)
- Aligning nix use approaches may need to serve different audiences (hApp devs, HPOS maintainers, Holo infrastructure devs)
- Lack of integration with IDEs (integrated development environments)
- Feedback from users is that nix use is not currently easy

## Aligned Possibility
- Merge approaches/uses into a single repo that is user friendly
- Use of nixpkgs overlays/modules/binary cache (so long as it doesn’t make things complicated & impact adoption toward 100 hApp goal)
- Use nix in ways that look like what devs are already used to doing/using
- Solution ensures dev projects are maintainable over time (UX that doesn’t break later)
- Everyone across Holo/chain teams works to maintain derivations

Points of concern:
- Maintaining backward-compatibility in this new shift is a strategic decision, but will likely be very hard to do.
  - Yegor attempted this before and ran into significant challenges.
- Having a mono-repo may give rise to dependencies in which holochain depends on holo. This is undesirable.

**Comment by alastairong** [comment]
> Use nix in ways that look like what devs are already used to doing/using
> Solution ensures dev projects are maintainable over time (UX that doesn’t break later)

Does dev here refer to all devs including 3rd party?

**Comment by alastairong** [comment]
CC: @yegortimoshenko @thedavidmeister 

Reading these notes and watching the video, please let me know if you agree with these high level statements on what a unified nix build system might look like across Holo/chain: (in no order of priority)
- We want to adhere much more closely to nix conventions and holo-nixpkg approach: binary caching, building artefacts in nix, nix overlays, etc.
- Third party hApp developers should not need to know any more nix than currently for Holonix
- We do not need to maintain backwards compatibility / identical UX, as long as it is of similar or easier complexity

**Comment by thedavidmeister** [comment]
@alastairong for what i've been working on yes, the target audience is third parties

**Comment by alastairong** [comment]
@steveeJ Closing this as I believe your work accomplishes or supersedes this
