### ISSUE TITLE
HoloPort name change is not saved on restart

### ISSUE THREAD

**Issue by alastairong** [Holo-Host/holo-nixpkgs#399]
**Issue:**
1. When I change my HoloPort name to "test name" in the settings menu it gets saved and displayed in browser
2. Browser console confirms `apollo mutation HposUpdateSettings` is called with a successful response
3. Further `apollo query HposSettings` are successful and show "test name" in the right field
4. Name is still "test name" after closing and reopening browser, and logging in again
5. Once HoloPort is rebooted, name reverts to "My HoloPort"

Expected behaviour
HoloPort name should be "testname" after reboot

**Steps to reproduce:**
As above

CC: @yegortimoshenko @peeech @SirRobLyon

**Comment by peeech** [comment]
Ah, of course! Locally (`/run/hpos-init/hpos-config.json`) file gets updated. But at each reboot system is re-inited from USB located `hpos-config.json`, which never gets updated!

**Comment by yegortimoshenko** [comment]
`/run/hpos-init/hpos-config.json` is a symlink to `hpos-config.json` located on USB drive.

**Comment by SirRobLyon** [comment]
So for this feature to persist beyond a reboot, does that mean Holocentral would have to do some work to update the hpos-config.json file?

**Comment by peeech** [comment]
> `/run/hpos-init/hpos-config.json` is a symlink to `hpos-config.json` located on USB drive.

Only until it is [replaced with a new file](https://github.com/Holo-Host/holo-nixpkgs/blob/develop/overlays/holo-nixpkgs/hpos-admin/hpos-admin.py#L50):
```
[root@hpos:/run/hpos-init]# ll hpos-config.json 
-rw------- 1 root root 317 Feb 28 21:48 hpos-config.json
```

**Comment by yegortimoshenko** [comment]
@peeech Great catch :)

**Comment by alastairong** [comment]
@SirRobLyon Yes seems like we'll have to deploy a fix.
