### ISSUE TITLE
Sometimes users cannot login due to TypeError: Response has unsupported MIME type

### ISSUE THREAD

**Issue by SirRobLyon** [Holo-Host/holo-nixpkgs#404]
![Screen Shot 2020-03-04 at 2 08 32 pm](https://user-images.githubusercontent.com/10045273/75921504-22f80000-5e59-11ea-93b3-ddc4c8f2a7ae.jpg)

**Comment by devinus** [comment]
Looks like this has been fixed: https://github.com/Holo-Host/holo-nixpkgs/commit/27d3678be8d76ae9d0c0d1c82c73699cfd5e91c8

**Comment by peeech** [comment]
Yes in fact, it's been fixed in #374. Thanks for keeping eye!

**Comment by SirRobLyon** [comment]
@philipbeadle is still seeing this show up for them.

**Comment by SirRobLyon** [comment]
![image](https://user-images.githubusercontent.com/10045273/76735223-5b061980-675c-11ea-894a-8146ff7869d3.png)

**Comment by peeech** [comment]
This has definitely been resolved in holo-nixpkgs. Now it is a different question why @philipbeadle is seeing this. Could be UI caching issue, could be hp updating issue (that it does not update). We are not gonna be able to properly debug this issue until we can see the guts of HPOS in cases like this.

My suggestion is that for all HPOS-es on staging we:
- enable ssh and open firewall port 22
- add Sam's and mine ssh key so we can ssh and look around
- add my and Sam's computer to the ZT network so we can tunnel to user's computers via it

**Comment by peeech** [comment]
cc @samrose @yegortimoshenko

**Comment by alastairong** [comment]
I don't think this issue has been closed by the ssh keys, only that now we can debug it

**Comment by alastairong** [comment]
Closing as does not seem to be an issue anymore.
