### ISSUE TITLE
update a list of ssh authorizedKeys.

### ISSUE THREAD

**Issue by peeech** [Holo-Host/holo-nixpkgs#416]
[This list of authorizedKeys](https://github.com/Holo-Host/holo-nixpkgs/blob/develop/profiles/logical/hpos/staged/default.nix#L8) needs to be updated and refreshed, according to the conversation from #404 .

**Comment by peeech** [comment]
I suggest splitting `staged` into two separate profiles: `staging` and `devs`. `staging would hold the keys of all those folks that would be allowed to access HPOS in QA, `devs` would grant access to packet development servers etc.

**Comment by yegortimoshenko** [comment]
I don't see an issue with adding everyone in QA to staged profile. The only access it grants is access to `hpos-1.holo.host` and `hpos-2.holo.host`.
