### ISSUE TITLE
Customer Issue: HP Reboot Loop every ~3 minutes due to holoportos-upgrade error seeking github repo that does not exist

### ISSUE THREAD

**Issue by SirRobLyon** [Holo-Host/holo-nixpkgs#421]
For more information, links to HP Support Pivotal Tracker Bug and journalctl log file, please see:

https://chat.holochain.org/holo/pl/4sfbwz9gnjfc3rqqqkk65xc7ow

**Comment by mmahut** [comment]
Looks like his machine did have corrupted nixpkgs in the early stages.

```
   992 Jan 12 23:49:08 nixos systemd[1]: Starting holoportos-upgrade.service...
   993 Jan 12 23:49:08 nixos i1vhxm397jrxaf62scbv04h259mgccfm-unit-script-holoportos-upgrade-start[800]: writing /etc/nixos/hardware-configuration.nix...
   994 Jan 12 23:49:08 nixos i1vhxm397jrxaf62scbv04h259mgccfm-unit-script-holoportos-upgrade-start[800]: warning: not overwriting existing /etc/nixos/configuration.nix
   995 Jan 12 23:49:11 nixos i1vhxm397jrxaf62scbv04h259mgccfm-unit-script-holoportos-upgrade-start[800]: unpacking channels...
   996 Jan 12 23:49:18 nixos i1vhxm397jrxaf62scbv04h259mgccfm-unit-script-holoportos-upgrade-start[800]: error: syntax error, unexpected $end, at /nix/store/7f4c0dzcxpsh8yha84kbgqkql10s50fz-nixpkgs/pkgs/top-level/impure.nix:1:1
   997 Jan 12 23:49:18 nixos i1vhxm397jrxaf62scbv04h259mgccfm-unit-script-holoportos-upgrade-start[800]: (use '--show-trace' to show detailed location information)
   998 Jan 12 23:49:18 nixos i1vhxm397jrxaf62scbv04h259mgccfm-unit-script-holoportos-upgrade-start[800]: building Nix...
```

This might have been a result of power failure during a switch or so. However, it did attempt to run ```holoportos-upgrade``` even when some of the command has failed. We might mitigate this change by https://github.com/Holo-Host/holoportOS/commit/48e41e1cd3ff5c98d5f80e4f5f5d6b7a796aeca4 cc @yegortimoshenko as that repository is now archived.

Can the customer try to boot an older generation (if there is some)?

**Comment by yegortimoshenko** [comment]
@mmahut I've unarchived `holoportOS`, https://github.com/Holo-Host/holoportOS/commit/48e41e1cd3ff5c98d5f80e4f5f5d6b7a796aeca4 LGTM.

**Comment by alastairong** [comment]
@mmahut Is there a next step for the customer?

**Comment by SirRobLyon** [comment]
@mmahut bump - I have another customer I'm meeting with tomorrow that has the same issue. Would be great to have a clear solution or steps to try.

**Comment by mmahut** [comment]
I don't think there is anything else to do than reinstall their holoports. @yegortimoshenko thoughts?

**Comment by alastairong** [comment]
@mmahut This would require providing a rescue image to them right?
