### ISSUE TITLE
[HPOS Shell CLI Bug] :: LLVM ERROR: IO failure on output stream: No space left on device

### ISSUE THREAD

**Issue by JettTech** [Holo-Host/holo-nixpkgs#424]
## Description
After entering nix-shell and attempting to run `hpos-shell`, I encounter an IO error, which states that there is no space left on the device (os error 28) and results in the build failing.

![Screenshot from 2020-03-26 10-35-52](https://user-images.githubusercontent.com/30459942/77768973-3be77180-7011-11ea-84d6-f7486a90163b.png)

xx: @alastairong @yegortimoshenko @peeech

**Comment by alastairong** [comment]
@mmahut Maybe this is something Marek can look into as a way to get more familiar with out setup

**Comment by mmahut** [comment]
@JettTech can you please elaborate why do you think this is a bug? From the error message, it seems you have run out of disk space, isn't it the case? Thank you.

**Comment by alastairong** [comment]
Stale
