### ISSUE TITLE
Create unique set of hashspaces for all installed DNAs

### ISSUE THREAD

**Issue by peeech** [Holo-Host/holo-nixpkgs#425]
Testers need ability to create new DHT hashspace for each testing round. This can be achieved by altering `.dna.json` file so that it produces unique hash for each testing round. 

The idea is to use a `uuid` key in json file:
```
  "uuid": "00000000-0000-0000-0000-000000000001",
```
For each testing round PR maintainer would update nix config to the new value and nix would build unique DNAs by altering "uuid" line in `.dna.json`.

**Comment by alastairong** [comment]
Fixed in https://github.com/Holo-Host/holo-nixpkgs/pull/498
