### ISSUE TITLE
Conflict between dnas with the same name

### ISSUE THREAD

**Issue by peeech** [Holo-Host/holo-nixpkgs#450]
**Description**
One DNA overwrites other DNA during build process.
In case two DNAs in HPOS have the same `xxx.dna.json` file name in the process of copying `DNAs` into the `/var/lib/holchain-conductor/dnas/` folder self-hosted DNA is overwritten by `holo-hosted` DNA.
Na error occurs, because names of the DNAs should be dna-hash based, rather than human created, which obviously leads to conflicts.

**How to reproduce**
Switch to branch that includes code from #439 
Pull in self-hosted dna [here](https://github.com/Holo-Host/holo-nixpkgs/blob/2020-04-14/update-conductor-config/profiles/logical/hpos/default.nix#L25)
Pull in holo-hosted dna [here](https://github.com/Holo-Host/holo-nixpkgs/blob/2020-04-14/update-conductor-config/profiles/logical/hpos/default.nix#L40)
make sure both DNAs are different, but they have the same `xxx.dna.json` file name
Rebuild HPOS
Watch for an error.

**Comment by marycamacho** [comment]
Can we resolve this with a process change for now @peeech ?
