### ISSUE TITLE
Remove dependency on Perl in NixOS

### ISSUE THREAD

**Issue by yegortimoshenko** [Holo-Host/holo-nixpkgs#55]
Perl is very difficult to cross-compile, so much so that doing that requires a third-party repo with alternative build system: https://github.com/NixOS/nixpkgs/blob/62ba206c88eb00534dd4c22ee97aaf78451ddefa/pkgs/development/interpreters/perl/default.nix#L178-L181

Since NixOS is becoming more and more of a cross-compilation friendly operating system, it would make sense to start dropping hard dependency on Perl and substitute scripts that depend on it one by one.

- [ ] `nixos/modules/installer/tools/nixos-generate-config.pl`
- [ ] `nixos/modules/programs/command-not-found/command-not-found.pl`
- [ ] `nixos/modules/config/update-users-groups.pl`
- [ ] `nixos/modules/system/boot/loader/grub/install-grub.pl`
- [ ] `nixos/modules/system/etc/setup-etc.pl`
- [ ] `nixos/modules/system/activation/switch-to-configuration.pl`

**Comment by yegortimoshenko** [comment]
Out of scope.

**Comment by samrose** [comment]
@yegortimoshenko is there an upstream effort doing this that you know of?

**Comment by yegortimoshenko** [comment]
Not that I know of :( I have added that to my personal backlog, want to take on this sometime.
