### ISSUE TITLE
Set up Hydra PostgreSQL database backup

### ISSUE THREAD

**Issue by yegortimoshenko** [Holo-Host/holo-nixpkgs#61]
High-priority: currently, PostgreSQL is not being backed up. It contains some data that requires durability (namely, non-declarative project setup).

**Comment by samrose** [comment]
I have addressed this with PR #294 

Notes on the PR indicate 3 steps needed to complete once the PR is approved

**Comment by samrose** [comment]
The PR referenced here was superceded by  d41dad2 and the deployment was completed with daily backups scheduled as of today.  (the steps above were completed in congruence with the commit referenced in this comment)
