### ISSUE TITLE
auto-upgrade.service reports a "false" error every upgrade cycle (10 min)

### ISSUE THREAD

**Issue by alastairong** [Holo-Host/holo-nixpkgs#617]
Auto-upgrade service reports that the upgrade fails every 10 minutes. This is because acme-default service "failed". This failure is because the certificate is still valid and did not need renewal.

Ideally we would clean this up so acme-default.service does not report failure when the certificate does not need renewal.

**Comment by alastairong** [comment]
CC: @zippy @peeech

**Comment by Br1ght0ne** [comment]
Looking into it.

**Comment by alastairong** [comment]
Fixed! Thanks @peeech
