### ISSUE TITLE
hpos-admin calls return 500

### ISSUE THREAD

**Issue by peeech** [Holo-Host/holo-nixpkgs#637]
Issue description:

Calls to GET `/api/v1/status` and PUT `/api/v1/profiles/development/features/ssh` are failing with 500. 

Expected behavior:
they don't :-)

Reason:
`hpos-admin-api` service (that is running as `admin-api` User) is trying to read from file `/root/.nix-channels` and write to file `/etc/nixos/hpos-admin-features.toml`. Both are in locations not accessible by `admin-api` User.

**Comment by peeech** [comment]
IMHO the location of both files should be `/val/lib/admin-api/`. They are needed only by `hpos-admin-api.service` and contain mutable information about the state of HPOS.

**Comment by alastairong** [comment]
Sure. Don't forget `~/.nix-revision` as well
