### ISSUE TITLE
Switch to using a device tree overlay for HoloPort Nano

### ISSUE THREAD

**Issue by abelianring** [Holo-Host/holo-nixpkgs#65]
This will allow to remove custom `extlinux-conf-builder` and check in HoloPort Nano device tree as overlay rather than patchset.

**Comment by yegortimoshenko** [comment]
Hooray, so this was implemented upstream: https://github.com/NixOS/nixpkgs/pull/60422

Now the only thing remains is to switch to device tree overlays here.

**Comment by alastairong** [comment]
Closed as nano is no longer in roadmap
