### ISSUE TITLE
Channel building and minions

### ISSUE THREAD

**Issue by alastairong** [Holo-Host/holo-nixpkgs#746]
holo-nixpkgs channel, which builds on Hydra as a superset of other builds, doesn’t build on 20.09 hydra, complaining about localhost not being either aarch64-linux or x86_64-darwin.

Example for Darwin (Hydra build):

a ‘x86_64-darwin’ with features {} is required to build ‘/nix/store/wrjzkmas5fnn440mxidmqg7zjsa0vyz7-hpos-holochain-api-modules-1.0.0.drv’, but I am a ‘x86_64-linux’ with features {benchmark, big-parallel, kvm, nixos-test} on ‘localhost’

When running nix-build on hydra-dev via SSH, with the derivation path taken from Details -> Derivation store path of the failed build (e.g. nix-build /nix/store/7f566bb12rvs4gxhaxgr56kj17vi9f2j-holo-nixpkgs.drv), the build completes. During the build, remote minion is used, for example, for copying packages to hydra-dev's /nix/store.

Afterwards, if the build on Hydra is to be restarted manually, it is immediately marked as successful.

**Comment by peeech** [comment]
fixed in #755
