### ISSUE TITLE
Build DNA on aarch64 machine

### ISSUE THREAD

**Issue by rgouzal** [Holo-Host/holo-nixpkgs#924]
Hi I am trying to build DNA I have managed to compile and install holo hosting app on Raspberry Pi 4 running Ubuntu OS   but I am having an issue when building the DNA with the below command:

`nix-build`

The error I am having:

```error: while evaluating the attribute 'handled' at /nix/store/rfspa8qp1vyhpqn8jznq3hjb9rffgnq6-nixpkgs/pkgs/stdenv/generic/check-meta.nix:251:7:
while evaluating 'handleEvalIssue' at /nix/store/rfspa8qp1vyhpqn8jznq3hjb9rffgnq6-nixpkgs/pkgs/stdenv/generic/check-meta.nix:147:38, called from /nix/store/rfspa8qp1vyhpqn8jznq3hjb9rffgnq6-nixpkgs/pkgs/stdenv/generic/check-meta.nix:252:14:
Package ‘holo-hosting-app’ in /nix/store/lg7xbkvdif97xsn9g0xskkcg2vsgxfbc-source/overlays/holo-nixpkgs/build-dna/default.nix:26 is not supported on ‘aarch64-linux’, refusing to evaluate.
```

**Comment by alastairong** [comment]
Hi Rgouzal. Holo-nixpkgs isn't intended for building DNAs. Best practice is to build the DNA separately and then install the compiled WASM (.happ) file, so that we don't get machine-specific hashspaces.

**Comment by rgouzal** [comment]
@alastairong Sorry I meant to write this issue on this repo:

[Holo-Host/holo-hosting-app](https://github.com/Holo-Host/holo-hosting-app)
